### ISSUE TITLE
Change PR name

### ISSUE THREAD

**Issue by CodingSpecies** [iamdevvalecha/Hacktoberfest-21-Open-First-PR#16]
@iamdevvalecha instead of naming pr `added myself`, I think it would be more clearer if they put `added username` instead. thank you.

**Comment by CodingSpecies** [comment]
Right now, I see this: 
![image](https://user-images.githubusercontent.com/70807500/135520099-9f13e4fa-a6ae-4e3f-a042-be4d95564aec.png)
and it is confusing. But if we say `add CodingSpecies` it would make more sense. Thank you.

**Comment by iamdevvalecha** [comment]
@CodingSpecies yep! but i don't have a bandwidth to do this.

**Comment by CodingSpecies** [comment]
@iamdevvalecha But, we could put somewhere in the readme to say: **Please call your pr name `Add Username`** . If you want I can do that. Thank you.

**Comment by CodingSpecies** [comment]
If so, please can you assign this to me? @iamdevvalecha

**Comment by iamdevvalecha** [comment]
@CodingSpecies 👍🏻 

> @iamdevvalecha But, we could put somewhere in the readme to say: **Please call your pr name `Add Username`** . If you want I can do that. Thank you.
